### ISSUE TITLE
There is way to cleanly evict all elements

### ISSUE THREAD

**Issue by esp32wrangler** [elastic/go-freelru#43]
I would like to cleanly drop the complete cache and call the evict callback on all elements. 
This is not currently possible, because:
- the Purge function doesn't call the evict callback
- Iterating over the Keys doesn't work, because there is no way to Get or Peek expired elements

Please add an option to Purge to call the eviction callback, or add a new function such as EvictAll

**Comment by rockdaboot** [comment]
Thanks for the request, sounds reasonable. I'll have a closer look at it soon.

**Comment by rockdaboot** [comment]
@esp32wrangler Please let me know if #49 satisfies your needs

**Comment by esp32wrangler** [comment]
> [@esp32wrangler](https://github.com/esp32wrangler) Please let me know if [#49](https://github.com/elastic/go-freelru/pull/49) satisfies your needs

Thanks for the quick fix! It looks good, please merge and tag it so I can properly test it in my app.
