### ISSUE TITLE
Lifetime only checked when a key is found

### ISSUE THREAD

**Issue by umanwizard** [elastic/go-freelru#47]
This code prints the numbers 1 through 1000:

```go
package main

import (
	"fmt"
	"time"

	lru "github.com/elastic/go-freelru"
)

func hashInt(foo int) uint32 {
	return uint32(foo)
}

func main() {
	cache, err := lru.NewSynced[int, int](1000, hashInt)
	if err != nil {
		panic("uhh")
	}

	for i := 0; i < 1000; i += 1 {
		cache.AddWithLifetime(i, i, time.Second)
		fmt.Printf("%d\n", cache.Len())
		time.Sleep(time.Second)
	}
}
```

This is because we only do a lifetime check when a key is found. So keys that are never checked again will never be evicted for exceeding their lifetime. They will only be evicted by the LRU policy.

**Comment by rockdaboot** [comment]
This is on purpose to avoid costly checks. But that doesn't work well in all situations and may cause resource leaks.
I think the main problem with the current approach is described in #43: control over expired items is required by the application code.

**Comment by rockdaboot** [comment]
@umanwizard Please have look at #49, any feedback appreciated. It works without introducing an internal go routine to regularly check for expired items. The application code can force it by explicitly calling `PurgeExpired()`, like in
```
	for i := 0; i < 1000; i += 1 {
		cache.AddWithLifetime(i, i, time.Second)
		fmt.Printf("%d\n", cache.Len())
		time.Sleep(time.Second)
		cache.PurgeExpired()
	}
```

**Comment by umanwizard** [comment]
That seems great to me.
