### ISSUE TITLE
Update GO version from 1.18 to at least 1.20

### ISSUE THREAD

**Issue by tkliner** [elastic/go-freelru#50]
Before Go 1.20:
Slices (including []byte) were not considered comparable, even though you could compare them with bytes.Equal. This was a limitation of the language.

Go 1.20 and later:
The comparable constraint was expanded to include all types that can be compared using == and !=, including slices like []byte.

So with 1.20 version we should able to use:

freelru.NewSyncedWithSize[[]byte, []byte](capacity, capacity, hashFn)

Once we are using freelru as cache for underlying DB this small change brings for us ability to avoid convert string to bytes etc.

**Comment by rockdaboot** [comment]
Thanks for the heads up.

But I am curious, what stops you from building your app with Go 1.20+?
The version 1.18 from `go.mod` is just a minimum requirement for building go-freelru (1.18 introduced generics). When you pull it in as a dependency, you can use any features of the Go version that you are building with.

**Comment by tkliner** [comment]
Hello,

thank you for your response, yes you are right. We can close this issue.
