### ISSUE TITLE
Request a shard version of LRU implementation.

### ISSUE THREAD

**Issue by phuslu** [elastic/go-freelru#7]
This LRU implementation is very impressive, and I believe its performance should be one of the top, thanks for this brilliant job!
But we really need a sharded version instead of synced version to perform well in a high parallelism. 

For example, a "shardedlru.go" like
```go
type ShardedLRU[K comparable, V any] struct {
	mu  []sync.RWMutex
	lru []*LRU[K, V]
}
```

Background: 
I happen to be currently implementing a simple lru cache as well, and would like to know how its performance compares to popular libraries. Here is my results on 
``` go
const (
	keysize     = 16
	cachesize   = 16384
	parallelism = 1000
)
```
```
goos: linux
goarch: amd64
cpu: Intel(R) Xeon(R) Silver 4216 CPU @ 2.10GHz
BenchmarkCloudflareGet
BenchmarkCloudflareGet-8   	100000000	        60.48 ns/op	      16 B/op	       1 allocs/op
BenchmarkElasticGet
BenchmarkElasticGet-8      	15093165	       424.4 ns/op	       0 B/op	       0 allocs/op
BenchmarkHashicorpGet
BenchmarkHashicorpGet-8    	27390493	       349.8 ns/op	       0 B/op	       0 allocs/op
BenchmarkPhusluGet
BenchmarkPhusluGet-8       	199958748	        30.45 ns/op	       0 B/op	       0 allocs/op
PASS
ok  	command-line-arguments	32.350s
```
Obviously freelru (and hashicorp) does not perform as well as it should (I think it should be top-notch) due to the use of a single lock.
Please refer to https://github.com/phuslu/lru?tab=readme-ov-file#benchmarks for the code, thanks.

**Comment by phuslu** [comment]
By the way, my latest version also use similar idioms to offload GC, thank you for your ideas!

see https://github.com/phuslu/lru/blob/master/rhh.go and https://github.com/phuslu/lru/blob/master/list.go

Could please add my lru lib to this bench?

**Comment by rockdaboot** [comment]
@phuslu Thanks for your feedback!

Yes to a sharded version. I recently made a parallel benchmark and ran into the slowness issue of SyncedLRU. A quick hack to add partitions / shards - similar to what you suggest - made it faster by a factor of 20x when using 1024 shards (tested with 20 cores locally). I'd let the user apply the number of shards.
Not to forget: the benchmarks create an extreme situation that you normally won't run into in production... A more realistic benchmark would just do e.g. 100 or 1000 of Get/Add calls per second and thus won't run into heavy lock contention. I think we need to keep this in mind when answering the question what we are optimizing for.
The good speed of FreeLRU was more of a "side-effect" - the priority was to optimize GC overhead with relatively small key/value types.

> Could please add my lru lib to this bench?

Would be a pleasure. You can also just make a PR :)

**Comment by phuslu** [comment]
looking forward~

**Comment by rockdaboot** [comment]
`ShardedLRU` is in `main`. I added a few parallel benchmarks (more to come).

Currently, the code is wrapped around `LRU`. But I'd like to reduce the number of allocs on creation. And the logic to determine the number of shards needs more thoughts.

Comments / reviews / tests are appreciated :)

**Comment by rockdaboot** [comment]
Benchmark results for `Get()`:
![bench](https://github.com/elastic/go-freelru/assets/2087964/e7db6caf-4c16-4c35-8ef5-96b24538dc92)

**Comment by phuslu** [comment]
Congrats! Can I say that this is meet my expectation? 😆 Now freelru is a good alternative for [fastcache](https://github.com/VictoriaMetrics/fastcache).

**Comment by rockdaboot** [comment]
> Congrats! Can I say that this is meet my expectation? 😆 Now freelru is a good alternative for [fastcache](https://github.com/VictoriaMetrics/fastcache).

😃 I guess so. Fastcache isn't an LRU, no eviction occurs, but likely ShardedLRU is faster (adding that to their benchmarks would possibly not please them !?).
 
> I mean although `[]struct{K,V}` still have GC overhead comparing with fastcache, but fastcache(and its friends) has their own overhead - marshaling/unmarshaling between []byte and go objects.

Yes, for pointer objects or structs that contain pointer objects, you should have your own memory "flattening" code (e.g. use slicing inside a large memory block) and store indices or pointers inside the LRU/cache.
